# Generated by Django 5.2.5 on 2025-09-19 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical_access", "migrations"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="doctor",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="passport_number",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="passport_series",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="phone",
        ),
        migrations.AddField(
            model_name="patient",
            name="medical_card_number",
            field=models.CharField(
                default="TEMP_CARD",
                help_text="Unique medical card number for the patient",
                max_length=20,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="terminal",
            name="mac_address",
            field=models.CharField(
                blank=True,
                help_text="Format: AA:BB:CC:DD:EE:FF",
                max_length=17,
                null=True,
                unique=True,
            ),
        ),
        migrations.DeleteModel(
            name="Doctor",
        ),
    ]
