# Generated by Django 5.2.5 on 2025-09-19 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical_access", "0001_remove_doctor_and_update_patient"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="integration",
            name="api_url",
        ),
        migrations.AlterField(
            model_name="integration",
            name="api_token",
            field=models.CharField(
                editable=False,
                help_text="Auto-generated secure token for partner authentication",
                max_length=255,
                unique=True,
            ),
        ),
    ]
