# Generated by Django 5.2.5 on 2025-09-05 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical_access", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("enter", "Enter"),
                    ("leave", "Leave"),
                    ("used", "Used"),
                    ("expired", "Expired"),
                ],
                default="active",
                max_length=16,
            ),
        ),
    ]
