# Generated by Django 5.2.5 on 2025-09-06 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical_access", "0002_alter_appointment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("super_admin", "Super Admin"),
                    ("admin", "Admin"),
                    ("receptionist", "Receptionist"),
                ],
                max_length=20,
            ),
        ),
    ]
