# Generated by Django 5.2.5 on 2025-09-06 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical_access", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="terminal",
            name="last_error",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="terminal",
            name="last_seen",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="terminal",
            name="reachable",
            field=models.BooleanField(default=False),
        ),
    ]
