# Generated by Django 5.2.5 on 2025-09-06 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical_access", "0004_terminal_last_error_terminal_last_seen_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="terminal",
            name="active",
            field=models.BooleanField(
                default=True, help_text="Set to False to skip this terminal"
            ),
        ),
    ]
