# Generated by Django 5.2.5 on 2025-08-29 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical_access", "0004_alter_patient_options_patient_address_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="door",
        ),
        migrations.AddField(
            model_name="door",
            name="room_number",
            field=models.CharField(
                blank=True,
                help_text="Room number (e.g., 101, A-12)",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="procedure",
            name="door",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="procedures",
                to="medical_access.door",
            ),
        ),
    ]
