# Generated by Django 5.2.5 on 2025-08-29 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical_access", "0005_remove_appointment_door_door_room_number_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="address",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="date_of_birth",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="email",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="emergency_contact",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="emergency_phone",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="user",
        ),
        migrations.RemoveField(
            model_name="procedure",
            name="door",
        ),
        migrations.AddField(
            model_name="appointment",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
