# Generated by Django 5.2.5 on 2025-09-06 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical_access", "0005_add_active_field_to_terminal"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScanLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "qr_payload",
                    models.CharField(
                        help_text="QR code or card number scanned", max_length=255
                    ),
                ),
                ("scan_time", models.DateTimeField(auto_now_add=True)),
                (
                    "scan_type",
                    models.CharField(
                        choices=[
                            ("qr", "QR Code"),
                            ("card", "Card"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "terminal_mode",
                    models.CharField(
                        choices=[
                            ("entry", "Entry"),
                            ("exit", "Exit"),
                            ("both", "Both"),
                        ],
                        help_text="Terminal mode when scanned",
                        max_length=10,
                    ),
                ),
                (
                    "is_valid",
                    models.BooleanField(
                        default=False, help_text="Whether the scan was valid/authorized"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about the scan"
                    ),
                ),
                (
                    "terminal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scan_logs",
                        to="medical_access.terminal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scan Log",
                "verbose_name_plural": "Scan Logs",
                "ordering": ["-scan_time"],
            },
        ),
    ]
