# Generated by Django 5.2.5 on 2025-09-01 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "medical_access",
            "0006_remove_appointment_notes_remove_patient_address_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("card_no", models.CharField(db_index=True, max_length=32)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("kiosk", "Kiosk"),
                            ("admin", "Admin Override"),
                            ("api", "API"),
                        ],
                        default="kiosk",
                        max_length=20,
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[("allow", "Allow"), ("deny", "Deny")], max_length=10
                    ),
                ),
                ("reason", models.CharField(max_length=200)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "operator",
                    models.CharField(
                        blank=True,
                        help_text="Staff member who performed override",
                        max_length=100,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="access_events",
                        to="medical_access.appointment",
                    ),
                ),
                (
                    "door",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="access_events",
                        to="medical_access.door",
                    ),
                ),
                (
                    "temporary_pass",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="access_events",
                        to="medical_access.temporarypass",
                    ),
                ),
            ],
            options={
                "verbose_name": "Access Event",
                "verbose_name_plural": "Access Events",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["card_no", "-timestamp"],
                        name="medical_acc_card_no_94bd02_idx",
                    ),
                    models.Index(
                        fields=["result", "-timestamp"],
                        name="medical_acc_result_8cc3e5_idx",
                    ),
                    models.Index(
                        fields=["source", "-timestamp"],
                        name="medical_acc_source_f99faa_idx",
                    ),
                ],
            },
        ),
    ]
