# Generated by Django 5.2.5 on 2025-09-06 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("medical_access", "0006_add_scan_log_model"),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScanLog',
        ),
    ]
