# Generated by Django 5.2.5 on 2025-09-04 08:46

from django.db import migrations, models
import django.db.models.deletion
import random
from django.utils import timezone
from datetime import timedelta


def migrate_doctor_data(apps, schema_editor):
    """Migrate Doctor data from User-based to direct fields"""
    Doctor = apps.get_model('medical_access', 'Doctor')
    User = apps.get_model('medical_access', 'User')
    
    for doctor in Doctor.objects.all():
        if hasattr(doctor, 'user') and doctor.user:
            doctor.first_name = doctor.user.first_name or 'Unknown'
            doctor.last_name = doctor.user.last_name or 'Doctor'
            doctor.save()


def migrate_appointment_data(apps, schema_editor):
    """Add QR code fields to existing appointments"""
    Appointment = apps.get_model('medical_access', 'Appointment')
    
    for appointment in Appointment.objects.all():
        if not appointment.card_no:
            # Generate 8-digit numeric card number
            appointment.card_no = str(random.randint(10000000, 99999999))
            appointment.qr_payload = appointment.card_no
            appointment.valid_from = timezone.now()
            appointment.valid_to = timezone.now() + timedelta(hours=24)
            appointment.save()


class Migration(migrations.Migration):

    dependencies = [
        ("medical_access", "0007_accessevent"),
    ]

    operations = [
        # Step 1: Add new fields to Doctor model
        migrations.AddField(
            model_name='doctor',
            name='first_name',
            field=models.CharField(max_length=50, default='Unknown'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='last_name',
            field=models.CharField(max_length=50, default='Doctor'),
            preserve_default=False,
        ),
        
        # Step 2: Migrate Doctor data
        migrations.RunPython(migrate_doctor_data),
        
        # Step 3: Remove User relationship from Doctor
        migrations.RemoveField(
            model_name='doctor',
            name='user',
        ),
        
        # Step 4: Add QR code fields to Appointment
        migrations.AddField(
            model_name='appointment',
            name='card_no',
            field=models.CharField(max_length=32, unique=True, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='qr_payload',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='valid_from',
            field=models.DateTimeField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='valid_to',
            field=models.DateTimeField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='used_at',
            field=models.DateTimeField(null=True, blank=True),
        ),
        
        # Step 5: Migrate Appointment data
        migrations.RunPython(migrate_appointment_data),
        
        # Step 6: Update Appointment status choices
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(max_length=16, choices=[('active', 'Active'), ('used', 'Used'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='active'),
        ),
        
        # Step 7: Update AccessEvent to remove temporary_pass reference
        migrations.RemoveField(
            model_name='accessevent',
            name='temporary_pass',
        ),
    ]
