# Generated by Django 5.2.5 on 2025-09-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical_access", "0005_add_active_field_to_terminal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="terminal",
            name="mode",
            field=models.CharField(
                choices=[("entry", "Entry"), ("exit", "Exit"), ("both", "Both")],
                default="entry",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="terminal",
            name="terminal_ip",
            field=models.GenericIPAddressField(unique=True),
        ),
        migrations.AddIndex(
            model_name="terminal",
            index=models.Index(
                fields=["mode", "active"], name="medical_acc_mode_7e0571_idx"
            ),
        ),
    ]
