# Generated by Django 5.2.5 on 2025-09-04 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("medical_access", "0008_auto_20250904_0846"),
    ]

    operations = []
