# Generated by Django 5.2.5 on 2025-09-07 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "medical_access",
            "0008_alter_terminal_mode_alter_terminal_terminal_ip_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="token",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="token_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="token_used_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
