# Generated by Django 5.2.5 on 2025-09-04 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical_access", "0009_auto_20250904_1032"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appointment",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Appointment",
                "verbose_name_plural": "Appointments",
            },
        ),
        migrations.AlterModelOptions(
            name="doctor",
            options={
                "ordering": ["last_name", "first_name"],
                "verbose_name": "Doctor",
                "verbose_name_plural": "Doctors",
            },
        ),
        migrations.AlterUniqueTogether(
            name="appointment",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="paid",
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name="TemporaryPass",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="is_active",
        ),
    ]
