# Generated by Django 5.2.5 on 2025-09-07 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("medical_access", "0009_add_token_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="card_number",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="used_at",
        ),
    ]
