# Generated by Django 5.2.5 on 2025-09-04 16:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_access', '0010_fix_foreign_key_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0.01, 'Price must be greater than 0')]),
        ),
    ]
