# Generated by Django 5.2.5 on 2025-09-07 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical_access", "0010_remove_card_number_field"),
    ]

    operations = [
        # Remove old token fields
        migrations.RemoveField(
            model_name='appointment',
            name='token',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='token_expires_at',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='token_used_at',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='qr_payload',
        ),
        
        # Add new simple QR code field
        migrations.AddField(
            model_name='appointment',
            name='qr_code',
            field=models.CharField(max_length=12, unique=True, null=True, blank=True),
        ),
        
        # Add used_at field
        migrations.AddField(
            model_name='appointment',
            name='used_at',
            field=models.DateTimeField(null=True, blank=True),
        ),
    ]
