# Generated by Django 5.2.5 on 2025-09-07 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical_access", "0011_auto_20250907_1420"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="appointments",
                to="medical_access.patient",
            ),
        ),
    ]
