# Generated by Django 5.2.5 on 2025-09-09 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("medical_access", "0003_alter_user_role"),
        ("medical_access", "0007_remove_scan_log_model"),
        ("medical_access", "0012_alter_appointment_patient"),
    ]

    operations = []
