# Generated by Django 5.2.5 on 2025-09-10 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical_access", "0013_merge_20250909_1437"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="external_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=128, null=True, unique=True
            ),
        ),
    ]
