# Generated by Django 5.2.5 on 2025-09-10 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical_access", "0014_add_external_id_to_appointment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Integration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Integration name (e.g., DMED, RemoteJobs)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "api_url",
                    models.URLField(
                        blank=True, help_text="Base API endpoint if needed", null=True
                    ),
                ),
                (
                    "api_token",
                    models.CharField(
                        editable=False,
                        help_text="Auto-generated secure token",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Enable/disable this integration"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Integration",
                "verbose_name_plural": "Integrations",
                "ordering": ["name"],
            },
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="external_id",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="qr_code",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="status",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="used_at",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="valid_from",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="valid_till",
        ),
        migrations.AlterField(
            model_name="appointment",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="appointments",
                to="medical_access.doctor",
            ),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="first_name",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="last_name",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="patient",
            name="first_name",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="patient",
            name="last_name",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="patient",
            name="passport_number",
            field=models.CharField(blank=True, default="", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="passport_series",
            field=models.CharField(blank=True, default="", max_length=10, null=True),
        ),
        migrations.CreateModel(
            name="QRCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=12, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("entered", "Entered"),
                            ("left", "Left"),
                            ("expired", "Expired"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("revoked", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "appointment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qr_code",
                        to="medical_access.appointment",
                    ),
                ),
            ],
            options={
                "verbose_name": "QR Code",
                "verbose_name_plural": "QR Codes",
                "ordering": ["-created_at"],
            },
        ),
    ]
