# Generated by Django migration for creating initial superadmin

from django.db import migrations
from django.contrib.auth import get_user_model

User = get_user_model()

def create_superadmin(apps, schema_editor):
    """Create initial superadmin user"""
    # Check if superuser already exists
    if User.objects.filter(is_superuser=True).exists():
        print("✅ Superuser already exists!")
        superuser = User.objects.filter(is_superuser=True).first()
        print(f"   Username: {superuser.username}")
        print(f"   Email: {superuser.email}")
        print(f"   Role: {superuser.role}")
        return
    
    # Create superuser
    username = "admin"
    email = "admin@payverify.com"
    password = "admin123"
    
    try:
        superuser = User.objects.create_superuser(
            username=username,
            email=email,
            password=password,
            role='super_admin'
        )
        
        print("✅ Superuser created successfully!")
        print(f"   Username: {username}")
        print(f"   Password: {password}")
        print(f"   Email: {email}")
        print(f"   Role: {superuser.role}")
        print("\n🔗 Admin URLs:")
        print("   Default Django Admin: http://localhost:8000/admin/")
        print("   Custom Medical Admin: http://localhost:8000/medical_admin/")
        print("   Web Dashboard: http://localhost:8000/medical_access/")
        
    except Exception as e:
        print(f"❌ Error creating superuser: {e}")

def reverse_create_superadmin(apps, schema_editor):
    """Reverse migration - delete the superadmin user"""
    try:
        User.objects.filter(username="admin", is_superuser=True).delete()
        print("✅ Superuser deleted successfully!")
    except Exception as e:
        print(f"❌ Error deleting superuser: {e}")

class Migration(migrations.Migration):

    dependencies = [
        ('medical_access', '0015_integration_remove_appointment_external_id_and_more'),
    ]

    operations = [
        migrations.RunPython(
            create_superadmin,
            reverse_create_superadmin,
            elidable=True,  # This migration can be elided when squashing migrations
        ),
    ]
